// src/pages/react/Counter.tsx
import { Actions } from './Actions'
import { Count } from './Count'
import { IsDivisibleByThree } from './IsDivisibleByThree'
import { useStore } from './store'

export const Counter = () => (
	<Actions actions={useStore.actions}>
		<Count useStore={useStore} />
		<IsDivisibleByThree useStore={useStore} />
	</Actions>
)

// src/pages/svelte/Counter.svelte
<script lang="ts">
	import type { store as SvelteStore } from './store'
	const { store }: { store: typeof SvelteStore } = $props()
</script>

<div>
	<button type="button" onclick={store.actions.increment}>+</button>
	<p>{store.state.count}</p>
	<p>{store.state.isDivisibleByThree ? 'Divisible by 3' : 'Not divisible by 3'}</p>
	<button type="button" onclick={store.actions.decrement}>-</button>
</div>
