// src/pages/svelte/Counter.svelte
<script lang="ts">
	import type { store as SvelteStore } from './store'
	const { store }: { store: typeof SvelteStore } = $props()
</script>

<div>
	<button type="button" onclick={store.actions.increment}>+</button>
	<p>{store.state.count}</p>
	<p>{store.state.isDivisibleByThree ? 'Divisible by 3' : 'Not divisible by 3'}</p>
	<button type="button" onclick={store.actions.decrement}>-</button>
</div>

// src/pages/solid/Counter.tsx
/** @jsxImportSource solid-js */
import type { store as Store } from './store'

export const Counter = (props: { store: typeof Store }) => (
	<div>
		<button type='button' onClick={props.store.actions.increment}>
			+
		</button>
		<p>{props.store.state.count}</p>
		<p>{props.store.state.isDivisibleByThree ? 'Divisible by 3' : 'Not divisible by 3'}</p>
		<button type='button' onClick={props.store.actions.decrement}>
			-
		</button>
	</div>
)
